/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
module.exports = {
    // By default, Docusaurus generates a sidebar from the docs folder structure
    // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
    someSidebar: [
        {
            type: "doc",
            id: "intro",
        },
        {
            type: "category",
            label: "JAVA基础",
            link: {
                type: "generated-index",
                title: "JAVA基础",
                slug: "/basics",
            },
            items: [
                {
                    type: "category",
                    label: "MySQL",
                    link: {
                        type: "doc",
                        // title: "MySQL",
                        id: "basics/mysql/mysql-intro",
                    },
                    items: [
                        // "basics/mysql/mysql-intro",
                        "basics/mysql/mysql-language",
                        "basics/mysql/mysql-function",
                        "basics/mysql/mysql-constraint",
                        "basics/mysql/mysql-query",
                        "basics/mysql/mysql-transaction",
                        "basics/mysql/mysql-norm",
                    ]
                },

            ],
            collapsed: false,
        }
    ]
};

